"""Configuration of search fields to map them with the elasticsearch
   equivalent.
   For those not defined here, the search key will be used to retrieve
   elasticsearch results
"""

fields = {
    "collection" : ["_collections"],
    "abstract": ["abstract.summary", "abstract.expansion", "abstract.number"],
    "author": ["authors.first_name", "authors.last_name",
               "authors.full_name", "_first_author.first_name",
               "_first_author.last_name", "_first_author.full_name",
               "authors.first_name.raw", "authors.last_name.raw",
               "authors.full_name.raw", "_first_author.first_name.raw",
               "_first_author.last_name.raw", "_first_author.full_name.raw",
               "_first_author.name_variations", "authors.name_variations"],
    "keyword": ["keywords.term"],
    "reference": [
        "reference.edoi",
        "reference.authors",
        "reference.misc",
        "reference.issue_number",
        "reference.order_number",
        "reference.page",
        "reference.report_number",
        "reference.title",
        "reference.url",
        "reference.volume",
        "reference.year"],
    "reportnumber": ["primary_report_number", "report_number.report_number" ],
    "title": ["title.title", "title.title.raw", "title.subtitle",
              "title.volume", "title.form", "title_additional.title",
              "title_additional.subtitle"
              "title_additional.misc", "title_additional.text.",
              "title_additional.part_number", "title_additional.part_name"],
    "journal": [
        "journal_info.doi",
        "journal_info.pagination",
        "journal_info.date",
        "journal_info.recid",
        "journal_info.note",
        "journal_info.title",
        "journal_info.url",
        "journal_info.volume",
        "journal_info.year",
        "journal_info.talk",
        "journal_info.cnum",
        "journal_info.reference"],
    "collaboration": ["_additional_corporate_names.collaboration"],
    "affiliation": ["_first_author.affiliation",
                    "_additional_authors.affiliation"],
    "exactauthor": ["_first_author.full_name", "_first_author.full_name.raw",
                    "_additional_authors.affiliation"],
    "caption": ["url.description"],
    "firstauthor": ["first_author.full_name", "first_author.full_name.raw"],
    "exactfirstauthor": ["first_author.full_name.raw"],
    "authorcount": ["number_of_authors"],
    "exacttitle": ["title.title", "title.title.raw", "title.subtitle",  # same as exacttitle
              "title.volume", "title.form", "title_additional.title",
              "title_additional.subtitle"
              "title_additional.misc", "title_additional.text.",
              "title_additional.part_number", "title_additional.part_name"],
    "itemcount": ["number_of_copies"],
    "raw_fields": ["title.raw", "authors.first_name.raw",
                   "authors.last_name.raw", "authors.full_name.raw",
                   "_first_author.first_name.raw",
                   "_first_author.last_name.raw",
                   "_first_author.full_name.raw",
                   "_first_author.name_variations", "authors.name_variations"],
    }
